name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/html

      - name: Deploy to GitHub Pages
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> 47c464b933e5b949f68a8098fad15d4b793f2265
